import { ArrowDownRight, ArrowUpRight, Banknote, Check, Cloud, FileText, Landmark, Plus, RefreshCw, Search, Trash2, TriangleAlert, WalletCards } from 'lucide-react';
import { useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { Button } from '../components/Button';
import { useCustomers } from '../hooks/useCustomers';
import { useFinance } from '../hooks/useFinance';
import type { FinanceTransaction, Invoice } from '../types';
import { formatShortDate, getLocalDateKey } from '../utils/date';

type View = 'Overview' | 'Transactions' | 'Invoices';
type TransactionDraft = Omit<FinanceTransaction, 'id' | 'createdAt'>;
type InvoiceDraft = Omit<Invoice, 'id' | 'createdAt'>;
const money = new Intl.NumberFormat('en-RW', { style: 'currency', currency: 'RWF', maximumFractionDigits: 0 });
const transactionEmpty = (): TransactionDraft => ({ type: 'Income', description: '', category: 'Sales', amount: 0, date: getLocalDateKey(), paymentMethod: 'Bank', reference: '' });
const invoiceEmpty = (): InvoiceDraft => ({ invoiceNumber: `INV-${Date.now().toString().slice(-6)}`, customerId: '', customerName: '', description: '', amount: 0, issueDate: getLocalDateKey(), dueDate: getLocalDateKey(), status: 'Draft' });

export function FinancePage() {
  const finance = useFinance(); const { customers } = useCustomers();
  const [view, setView] = useState<View>('Overview'); const [query, setQuery] = useState('');
  const [transaction, setTransaction] = useState(transactionEmpty); const [invoice, setInvoice] = useState(invoiceEmpty);
  const today = getLocalDateKey(); const month = today.slice(0, 7);
  const summary = useMemo(() => {
    const current = finance.transactions.filter((item) => item.date.startsWith(month));
    const income = current.filter((item) => item.type === 'Income').reduce((sum, item) => sum + item.amount, 0);
    const expenses = current.filter((item) => item.type === 'Expense').reduce((sum, item) => sum + item.amount, 0);
    const receivables = finance.invoices.filter((item) => ['Sent', 'Overdue'].includes(item.status)).reduce((sum, item) => sum + item.amount, 0);
    return { income, expenses, net: income - expenses, receivables };
  }, [finance.invoices, finance.transactions, month]);
  const transactions = finance.transactions.filter((item) => `${item.description} ${item.category} ${item.reference}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => b.date.localeCompare(a.date));
  const invoices = finance.invoices.map((item) => item.status === 'Sent' && item.dueDate < today ? { ...item, status: 'Overdue' as const } : item).filter((item) => `${item.invoiceNumber} ${item.customerName} ${item.description}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => a.dueDate.localeCompare(b.dueDate));

  function submitTransaction(event: FormEvent) { event.preventDefault(); if (!transaction.description.trim() || transaction.amount <= 0) return; finance.createTransaction({ ...transaction, description: transaction.description.trim(), amount: Number(transaction.amount) }); setTransaction(transactionEmpty()); }
  function submitInvoice(event: FormEvent) { event.preventDefault(); if (!invoice.customerName || !invoice.invoiceNumber.trim() || invoice.amount <= 0) return; const next = { ...invoice, invoiceNumber: invoice.invoiceNumber.trim(), amount: Number(invoice.amount) }; finance.createInvoice(next); if (next.status === 'Paid') finance.createTransaction({ type: 'Income', description: `Payment for ${next.invoiceNumber}`, category: 'Invoice payment', amount: next.amount, date: next.issueDate, paymentMethod: 'Bank', reference: next.invoiceNumber }); setInvoice(invoiceEmpty()); }
  function chooseCustomer(id: string) { const customer = customers.find((item) => item.id === id); setInvoice({ ...invoice, customerId: id, customerName: customer?.name ?? '' }); }
  function markPaid(item: Invoice) { finance.updateInvoice(item.id, { status: 'Paid' }); finance.createTransaction({ type: 'Income', description: `Payment for ${item.invoiceNumber}`, category: 'Invoice payment', amount: item.amount, date: today, paymentMethod: 'Bank', reference: item.invoiceNumber }); }

  return <div className="space-y-6">
    <section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-brand-orange">Finance</p><h1 className="mt-2 text-3xl font-black">Cash flow control</h1><p className="mt-2 max-w-2xl text-gray-500">Track money in, money out, invoices, and payments due from one operating view.</p></div><div className="flex rounded-md bg-gray-100 p-1">{(['Overview', 'Transactions', 'Invoices'] as View[]).map((item) => <button key={item} onClick={() => setView(item)} className={`min-h-9 rounded-md px-3 text-sm font-bold ${view === item ? 'bg-white shadow-sm' : 'text-gray-500'}`}>{item}</button>)}</div></section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={ArrowUpRight} label="Income this month" value={summary.income} tone="green" /><Metric icon={ArrowDownRight} label="Expenses this month" value={summary.expenses} tone="red" /><Metric icon={WalletCards} label="Net cash flow" value={summary.net} tone={summary.net >= 0 ? 'green' : 'red'} /><Metric icon={FileText} label="Outstanding invoices" value={summary.receivables} tone="orange" /></section>

    <section className={`flex flex-col justify-between gap-3 rounded-md border p-4 shadow-sm sm:flex-row sm:items-center ${finance.syncError ? 'border-red-200 bg-red-50' : 'border-gray-200 bg-white'}`}><div className="flex gap-3"><div className={`grid h-10 w-10 place-items-center rounded-md ${finance.syncError ? 'bg-red-100 text-red-700' : 'bg-orange-50 text-brand-orange'}`}>{finance.syncError ? <TriangleAlert size={19} /> : <Cloud size={19} />}</div><div><p className="font-bold">{finance.syncError ? 'Finance sync needs attention' : 'Finance cloud sync'}</p><p className="mt-1 text-sm text-gray-500">{finance.syncError || (finance.syncing ? 'Syncing finance records...' : 'Financial records are shared securely across your devices.')}</p></div></div><button onClick={finance.syncFromCloud} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-md bg-white px-4 text-sm font-bold ring-1 ring-gray-200"><RefreshCw size={16} className={finance.syncing ? 'animate-spin' : ''} />Sync now</button></section>

    {view !== 'Invoices' ? <form onSubmit={submitTransaction} className="rounded-md border border-gray-200 bg-white p-5 shadow-sm"><div><h2 className="text-lg font-black">Record transaction</h2><p className="mt-1 text-sm text-gray-500">Add verified income or business expenses.</p></div><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Field label="Type"><select value={transaction.type} onChange={(e) => setTransaction({ ...transaction, type: e.target.value as TransactionDraft['type'] })} className="control"><option>Income</option><option>Expense</option></select></Field><Field label="Description" wide><input required value={transaction.description} onChange={(e) => setTransaction({ ...transaction, description: e.target.value })} className="control" placeholder="What was this payment for?" /></Field><Field label="Amount (RWF)"><input required type="number" min="1" value={transaction.amount || ''} onChange={(e) => setTransaction({ ...transaction, amount: Number(e.target.value) })} className="control" /></Field><Field label="Category"><input value={transaction.category} onChange={(e) => setTransaction({ ...transaction, category: e.target.value })} className="control" /></Field><Field label="Date"><input type="date" value={transaction.date} onChange={(e) => setTransaction({ ...transaction, date: e.target.value })} className="control" /></Field><Field label="Payment method"><select value={transaction.paymentMethod} onChange={(e) => setTransaction({ ...transaction, paymentMethod: e.target.value as TransactionDraft['paymentMethod'] })} className="control"><option>Cash</option><option>Bank</option><option>Mobile Money</option><option>Card</option><option>Other</option></select></Field><Field label="Reference"><input value={transaction.reference} onChange={(e) => setTransaction({ ...transaction, reference: e.target.value })} className="control" placeholder="Receipt or transfer ID" /></Field></div><div className="mt-5 flex justify-end"><Button type="submit"><Plus size={16} />Save transaction</Button></div></form> : null}

    {view !== 'Transactions' ? <form onSubmit={submitInvoice} className="rounded-md border border-gray-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Create invoice</h2><p className="mt-1 text-sm text-gray-500">Track what customers owe and when payment is due.</p><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Field label="Invoice number"><input required value={invoice.invoiceNumber} onChange={(e) => setInvoice({ ...invoice, invoiceNumber: e.target.value })} className="control" /></Field><Field label="Customer"><select required value={invoice.customerId} onChange={(e) => chooseCustomer(e.target.value)} className="control"><option value="">Select customer</option>{customers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Amount (RWF)"><input required type="number" min="1" value={invoice.amount || ''} onChange={(e) => setInvoice({ ...invoice, amount: Number(e.target.value) })} className="control" /></Field><Field label="Status"><select value={invoice.status} onChange={(e) => setInvoice({ ...invoice, status: e.target.value as InvoiceDraft['status'] })} className="control"><option>Draft</option><option>Sent</option><option>Paid</option><option>Cancelled</option></select></Field><Field label="Description" wide><input value={invoice.description} onChange={(e) => setInvoice({ ...invoice, description: e.target.value })} className="control" /></Field><Field label="Issue date"><input type="date" value={invoice.issueDate} onChange={(e) => setInvoice({ ...invoice, issueDate: e.target.value })} className="control" /></Field><Field label="Due date"><input type="date" value={invoice.dueDate} onChange={(e) => setInvoice({ ...invoice, dueDate: e.target.value })} className="control" /></Field></div><div className="mt-5 flex justify-end"><Button type="submit"><Plus size={16} />Create invoice</Button></div></form> : null}

    <label className="flex min-h-11 items-center gap-2 rounded-md border border-gray-200 bg-white px-3 shadow-sm"><Search size={17} className="text-gray-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="w-full outline-none" placeholder="Search financial records" /></label>
    {view !== 'Invoices' ? <Ledger items={transactions} onDelete={finance.deleteTransaction} /> : null}
    {view !== 'Transactions' ? <InvoiceList items={invoices} onPaid={markPaid} onDelete={finance.deleteInvoice} /> : null}
  </div>;
}

function Field({ label, wide, children }: { label: string; wide?: boolean; children: ReactNode }) { return <label className={`space-y-2 ${wide ? 'lg:col-span-2' : ''}`}><span className="text-sm font-semibold text-gray-700">{label}</span>{children}</label>; }
function Metric({ icon: Icon, label, value, tone }: { icon: typeof Landmark; label: string; value: number; tone: string }) { const color = tone === 'green' ? 'text-emerald-700 bg-emerald-50' : tone === 'red' ? 'text-red-700 bg-red-50' : 'text-orange-700 bg-orange-50'; return <article className="rounded-md border border-gray-200 bg-white p-5 shadow-sm"><div className={`grid h-10 w-10 place-items-center rounded-md ${color}`}><Icon size={19} /></div><p className="mt-4 text-sm font-semibold text-gray-500">{label}</p><p className="mt-1 text-2xl font-black">{money.format(value)}</p></article>; }
function Ledger({ items, onDelete }: { items: FinanceTransaction[]; onDelete: (id: string) => void }) { return <section className="overflow-hidden rounded-md border border-gray-200 bg-white shadow-sm"><div className="border-b border-gray-100 p-5"><h2 className="text-lg font-black">Transaction ledger</h2></div>{items.length ? items.map((item) => <div key={item.id} className="flex flex-col gap-3 border-b border-gray-100 p-5 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><div className={`grid h-10 w-10 place-items-center rounded-md ${item.type === 'Income' ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-700'}`}>{item.type === 'Income' ? <ArrowUpRight size={18} /> : <ArrowDownRight size={18} />}</div><div><p className="font-bold">{item.description}</p><p className="mt-1 text-sm text-gray-500">{item.category} · {formatShortDate(item.date)} · {item.paymentMethod}</p></div></div><div className="flex items-center justify-between gap-4 sm:justify-end"><p className={`font-black ${item.type === 'Income' ? 'text-emerald-700' : 'text-red-700'}`}>{item.type === 'Income' ? '+' : '-'}{money.format(item.amount)}</p><Button variant="danger" className="h-9 w-9 px-0" onClick={() => onDelete(item.id)} aria-label="Delete transaction"><Trash2 size={15} /></Button></div></div>) : <Empty text="No transactions recorded yet" icon={Banknote} />}</section>; }
function InvoiceList({ items, onPaid, onDelete }: { items: Invoice[]; onPaid: (item: Invoice) => void; onDelete: (id: string) => void }) { return <section className="overflow-hidden rounded-md border border-gray-200 bg-white shadow-sm"><div className="border-b border-gray-100 p-5"><h2 className="text-lg font-black">Invoices and receivables</h2></div>{items.length ? items.map((item) => <div key={item.id} className="flex flex-col gap-4 border-b border-gray-100 p-5 last:border-0 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-black">{item.invoiceNumber}</p><span className={`rounded-md px-2 py-1 text-xs font-bold ${item.status === 'Paid' ? 'bg-emerald-50 text-emerald-700' : item.status === 'Overdue' ? 'bg-red-50 text-red-700' : 'bg-gray-100 text-gray-600'}`}>{item.status}</span></div><p className="mt-1 text-sm text-gray-500">{item.customerName} · Due {formatShortDate(item.dueDate)}</p><p className="mt-1 text-sm text-gray-500">{item.description}</p></div><div className="flex flex-wrap items-center gap-2"><p className="mr-2 text-lg font-black">{money.format(item.amount)}</p>{!['Paid', 'Cancelled'].includes(item.status) ? <Button variant="secondary" onClick={() => onPaid(item)}><Check size={16} />Mark paid</Button> : null}<Button variant="danger" className="h-10 w-10 px-0" onClick={() => onDelete(item.id)} aria-label="Delete invoice"><Trash2 size={16} /></Button></div></div>) : <Empty text="No invoices created yet" icon={FileText} />}</section>; }
function Empty({ text, icon: Icon }: { text: string; icon: typeof Landmark }) { return <div className="p-10 text-center"><Icon className="mx-auto text-gray-300" size={32} /><p className="mt-3 font-bold text-gray-500">{text}</p></div>; }
