import { Building2, Check, ChevronRight, CircleUserRound, Rocket, ShieldCheck } from 'lucide-react';
import { useState, type FormEvent, type ReactNode } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Button } from '../components/Button';
import { useWorkspace } from '../hooks/useWorkspace';
import { completeWorkspaceSetup, createWorkspace, inviteWorkspaceMember, type WorkspaceSetup } from '../services/workspaceService';

const modules = ['Tasks', 'Projects', 'Customers', 'Calendar', 'Reminders', 'Notes', 'Goals', 'Finance', 'Reports'];
const initial: WorkspaceSetup = { name: '', type: 'Company', country: 'RW', currency: 'RWF', timezone: 'Africa/Kigali', industry: '', enabledModules: modules, plan: 'Business' };

export function OnboardingPage() {
  const { activeWorkspace, refresh } = useWorkspace(); const [params] = useSearchParams(); const navigate = useNavigate();
  const creatingNew = params.get('new') === '1'; const [setup, setSetup] = useState<WorkspaceSetup>(() => creatingNew ? initial : { ...initial, name: activeWorkspace?.name ?? '', type: activeWorkspace?.type ?? 'Company', country: activeWorkspace?.country ?? 'RW', currency: activeWorkspace?.currency ?? 'RWF', timezone: activeWorkspace?.timezone ?? 'Africa/Kigali', industry: activeWorkspace?.industry ?? '', enabledModules: activeWorkspace?.enabledModules?.length ? activeWorkspace.enabledModules : modules, plan: activeWorkspace?.plan ?? 'Business' });
  const [invites, setInvites] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  function toggleModule(name: string) { setSetup((current) => ({ ...current, enabledModules: current.enabledModules.includes(name) ? current.enabledModules.filter((item) => item !== name) : [...current.enabledModules, name] })); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!setup.name.trim() || !setup.enabledModules.length) return; setBusy(true); setMessage(''); try { const workspaceId = creatingNew ? await createWorkspace({ ...setup, name: setup.name.trim() }) : activeWorkspace ? (await completeWorkspaceSetup(activeWorkspace.id, { ...setup, name: setup.name.trim() }), activeWorkspace.id) : ''; if (!workspaceId) throw new Error('Workspace could not be created.'); const emails = invites.split(',').map((email) => email.trim()).filter(Boolean); await Promise.all(emails.map((email) => inviteWorkspaceMember(workspaceId, email, 'Member'))); refresh(); window.setTimeout(() => { navigate('/'); window.location.reload(); }, 300); } catch (error) { setMessage(error instanceof Error ? error.message : 'Workspace setup failed.'); setBusy(false); } }
  return <div className="mx-auto max-w-4xl space-y-6"><section className="overflow-hidden rounded-md bg-brand-black p-6 text-white shadow-premium md:p-8"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-md bg-brand-orange"><Rocket size={22} /></div><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-orange">Workspace setup</p><h1 className="mt-1 text-3xl font-black">{creatingNew ? 'Create another workspace' : 'Welcome to ENs'}</h1></div></div><p className="mt-4 max-w-2xl leading-7 text-gray-300">Set up a private operating space for yourself or your company. Its data and team access stay separate from every other workspace.</p></section>
    <form onSubmit={submit} className="space-y-6"><section className="rounded-md border border-gray-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">1. Workspace type</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><TypeButton active={setup.type === 'Personal'} icon={CircleUserRound} title="Personal" text="For your own tasks, notes, goals, and finances." onClick={() => setSetup({ ...setup, type: 'Personal', plan: 'Personal' })} /><TypeButton active={setup.type === 'Company'} icon={Building2} title="Company" text="For teams, customers, projects, finance, and reports." onClick={() => setSetup({ ...setup, type: 'Company', plan: setup.plan === 'Personal' ? 'Business' : setup.plan })} /></div></section>
      <section className="rounded-md border border-gray-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">2. Organization details</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label={setup.type === 'Company' ? 'Company name' : 'Workspace name'}><input required value={setup.name} onChange={(event) => setSetup({ ...setup, name: event.target.value })} className="control" placeholder={setup.type === 'Company' ? 'Company name' : 'My workspace'} /></Field><Field label="Industry"><input value={setup.industry} onChange={(event) => setSetup({ ...setup, industry: event.target.value })} className="control" placeholder="Technology, retail, consulting..." /></Field><Field label="Country"><select value={setup.country} onChange={(event) => setSetup({ ...setup, country: event.target.value })} className="control"><option value="RW">Rwanda</option><option value="KE">Kenya</option><option value="UG">Uganda</option><option value="TZ">Tanzania</option><option value="US">United States</option><option value="OTHER">Other</option></select></Field><Field label="Currency"><select value={setup.currency} onChange={(event) => setSetup({ ...setup, currency: event.target.value })} className="control"><option>RWF</option><option>USD</option><option>EUR</option><option>KES</option><option>UGX</option><option>TZS</option></select></Field><Field label="Timezone"><select value={setup.timezone} onChange={(event) => setSetup({ ...setup, timezone: event.target.value })} className="control"><option>Africa/Kigali</option><option>Africa/Nairobi</option><option>Africa/Kampala</option><option>Africa/Dar_es_Salaam</option><option>UTC</option></select></Field><Field label="Plan"><select value={setup.plan} onChange={(event) => setSetup({ ...setup, plan: event.target.value as WorkspaceSetup['plan'] })} className="control"><option>Personal</option><option>Business</option><option>Professional</option></select></Field></div></section>
      <section className="rounded-md border border-gray-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">3. Choose modules</h2><p className="mt-1 text-sm text-gray-500">You can change these later in workspace settings.</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{modules.map((module) => <button type="button" key={module} onClick={() => toggleModule(module)} className={`flex min-h-11 items-center justify-between rounded-md border px-3 text-sm font-bold ${setup.enabledModules.includes(module) ? 'border-orange-300 bg-orange-50 text-brand-black' : 'border-gray-200 text-gray-500'}`}>{module}{setup.enabledModules.includes(module) ? <Check size={16} className="text-brand-orange" /> : null}</button>)}</div></section>
      {setup.type === 'Company' ? <section className="rounded-md border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ShieldCheck size={20} className="text-brand-orange" /><h2 className="text-lg font-black">4. Invite your team</h2></div><p className="mt-1 text-sm text-gray-500">Optional. Separate multiple email addresses with commas.</p><input value={invites} onChange={(event) => setInvites(event.target.value)} className="control mt-4" placeholder="manager@company.com, team@company.com" /></section> : null}
      {message ? <p className="rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-700">{message}</p> : null}<div className="flex justify-end"><Button type="submit" disabled={busy}>{busy ? 'Setting up...' : 'Finish setup'}<ChevronRight size={17} /></Button></div>
    </form></div>;
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="space-y-2"><span className="text-sm font-semibold text-gray-700">{label}</span>{children}</label>; }
function TypeButton({ active, icon: Icon, title, text, onClick }: { active: boolean; icon: typeof Building2; title: string; text: string; onClick: () => void }) { return <button type="button" onClick={onClick} className={`flex min-h-28 gap-3 rounded-md border p-4 text-left ${active ? 'border-orange-300 bg-orange-50' : 'border-gray-200 hover:bg-gray-50'}`}><Icon size={22} className={active ? 'text-brand-orange' : 'text-gray-400'} /><span><strong className="block">{title}</strong><span className="mt-1 block text-sm leading-6 text-gray-500">{text}</span></span></button>; }
