import { Building2, Crown, MailPlus, RefreshCw, ShieldCheck, Trash2, UserRoundCog, Users } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { Button } from '../components/Button';
import { useWorkspace } from '../hooks/useWorkspace';
import { inviteWorkspaceMember, loadWorkspaceMembers, removeWorkspaceMember, updateWorkspaceMemberRole } from '../services/workspaceService';
import type { WorkspaceMember, WorkspaceRole } from '../types';

export function TeamPage() {
  const { activeWorkspace, loading, refresh } = useWorkspace(); const [members, setMembers] = useState<WorkspaceMember[]>([]); const [email, setEmail] = useState(''); const [role, setRole] = useState<'Admin' | 'Member'>('Member'); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const canManage = activeWorkspace?.role === 'Owner' || activeWorkspace?.role === 'Admin';
  function load() { if (!activeWorkspace) return; setBusy(true); loadWorkspaceMembers(activeWorkspace.id).then(setMembers).catch((error) => setMessage(error instanceof Error ? error.message : 'Could not load members.')).finally(() => setBusy(false)); }
  useEffect(load, [activeWorkspace?.id]);
  async function invite(event: FormEvent) { event.preventDefault(); if (!activeWorkspace || !email.trim()) return; setBusy(true); setMessage(''); try { await inviteWorkspaceMember(activeWorkspace.id, email, role); setEmail(''); setMessage('Invitation saved. The user will join automatically after signing in with this email.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Invitation failed.'); } finally { setBusy(false); } }
  async function changeRole(member: WorkspaceMember, nextRole: WorkspaceRole) { if (nextRole === 'Owner') return; await updateWorkspaceMemberRole(member.id, nextRole); load(); }
  async function remove(member: WorkspaceMember) { await removeWorkspaceMember(member.id); load(); }
  return <div className="space-y-6"><section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-brand-orange">Team & permissions</p><h1 className="mt-2 text-3xl font-black">Workspace access</h1><p className="mt-2 max-w-2xl text-gray-500">Invite people, assign roles, and keep company data inside the correct workspace.</p></div><Button variant="secondary" onClick={() => { refresh(); load(); }}><RefreshCw size={16} className={loading || busy ? 'animate-spin' : ''} />Refresh</Button></section>
    <section className="grid gap-4 sm:grid-cols-3"><Stat icon={Building2} label="Workspace" value={activeWorkspace?.name ?? 'Not ready'} /><Stat icon={Users} label="Active members" value={String(members.length)} /><Stat icon={ShieldCheck} label="Your role" value={activeWorkspace?.role ?? 'None'} /></section>
    {canManage ? <form onSubmit={invite} className="rounded-md border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><MailPlus size={20} className="text-brand-orange" /><h2 className="text-lg font-black">Invite team member</h2></div><p className="mt-2 text-sm text-gray-500">The invitation is linked to the email address. Email delivery will be added in the next phase.</p><div className="mt-5 grid gap-4 md:grid-cols-[1fr_180px_auto]"><input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} className="control" placeholder="team@company.com" /><select value={role} onChange={(event) => setRole(event.target.value as 'Admin' | 'Member')} className="control"><option>Member</option><option>Admin</option></select><Button type="submit" disabled={busy}><MailPlus size={16} />Create invitation</Button></div>{message ? <p className="mt-4 rounded-md bg-gray-50 p-3 text-sm text-gray-600">{message}</p> : null}</form> : <p className="rounded-md border border-orange-200 bg-orange-50 p-4 text-sm text-orange-800">Only workspace owners and admins can invite or manage members.</p>}
    <section className="overflow-hidden rounded-md border border-gray-200 bg-white shadow-sm"><div className="border-b border-gray-100 p-5"><h2 className="text-lg font-black">Workspace members</h2></div>{members.length ? members.map((member) => <div key={member.id} className="flex flex-col gap-3 border-b border-gray-100 p-5 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-md bg-gray-100 text-gray-600">{member.role === 'Owner' ? <Crown size={18} /> : <UserRoundCog size={18} />}</div><div><p className="font-bold">{member.fullName || member.email}</p><p className="text-sm text-gray-500">{member.email}</p></div></div><div className="flex items-center gap-2">{canManage && member.role !== 'Owner' ? <><select value={member.role} onChange={(event) => void changeRole(member, event.target.value as WorkspaceRole)} className="min-h-9 rounded-md border border-gray-200 bg-white px-3 text-sm font-bold"><option>Member</option><option>Admin</option></select><Button variant="danger" className="h-9 w-9 px-0" onClick={() => void remove(member)} aria-label="Remove member"><Trash2 size={15} /></Button></> : <span className="rounded-md bg-orange-50 px-3 py-2 text-xs font-bold text-orange-700">{member.role}</span>}</div></div>) : <p className="p-8 text-center text-sm text-gray-500">{busy ? 'Loading workspace members...' : 'No members are available yet.'}</p>}</section>
  </div>;
}
function Stat({ icon: Icon, label, value }: { icon: typeof Users; label: string; value: string }) { return <article className="rounded-md border border-gray-200 bg-white p-5 shadow-sm"><Icon size={21} className="text-brand-orange" /><p className="mt-4 text-sm font-semibold text-gray-500">{label}</p><p className="mt-1 text-xl font-black">{value}</p></article>; }
